export const ROUTES = [
  { name: "Home", title: "Landing Page", group: "Public" },
  { name: "About", title: "About", group: "Public" },
  { name: "Contact", title: "Contact", group: "Public" },
  { name: "Login", title: "Login", group: "Public" },
  { name: "ClientOverview", title: "Client Overview", group: "Client" },
  { name: "ClientOrders", title: "Client Orders", group: "Client" },
  { name: "OrderTracking", title: "Order Tracking", group: "Client" },
  { name: "ClientMeasurements", title: "Client Measurements", group: "Client" },
  { name: "ClientMarketplace", title: "Client Marketplace", group: "Client" },
  { name: "ProductDetails", title: "Product Details", group: "Client" },
  { name: "ShoppingCart", title: "Shopping Cart", group: "Client" },
  { name: "CustomOrderForm", title: "Custom Order Form", group: "Client" },
  { name: "VirtualTryOn", title: "Virtual Try On", group: "Client" },
  { name: "DesignerOverview", title: "Designer Overview", group: "Designer" },
  { name: "DesignerOrders", title: "Designer Orders", group: "Designer" },
  {
    name: "DesignerOrderDetails",
    title: "Designer Order Details",
    group: "Designer",
  },
  { name: "DesignerOrderNew", title: "Designer New Order", group: "Designer" },
  {
    name: "DesignerCustomOrderNew",
    title: "Designer New Custom Order",
    group: "Designer",
  },
  { name: "DesignerClients", title: "Designer Clients", group: "Designer" },
  { name: "ClientDetails", title: "Client Details", group: "Designer" },
  { name: "ManageDesigns", title: "Manage Designs", group: "Designer" },
  { name: "DesignerProducts", title: "Designer Products", group: "Designer" },
  {
    name: "DesignerProductDetails",
    title: "Designer Product Details",
    group: "Designer",
  },
  { name: "DesignerProductNew", title: "Designer New Product", group: "Designer" },
  {
    name: "DesignerMeasurements",
    title: "Designer Measurements",
    group: "Designer",
  },
  {
    name: "DesignerShopSettings",
    title: "Designer Shop Settings",
    group: "Designer",
  },
  { name: "DesignerTryOn", title: "Designer Try On", group: "Designer" },
  { name: "DesignerMessages", title: "Designer Messages", group: "Designer" },
  {
    name: "DesignerMessageThread",
    title: "Designer Message Thread",
    group: "Designer",
  },
  { name: "DesignerPortfolio", title: "Designer Portfolio", group: "Designer" },
  { name: "Profile", title: "Profile", group: "Account" },
  { name: "Settings", title: "Settings", group: "Account" },
  { name: "NotFound", title: "Not Found", group: "System" },
];

export const ROUTE_GROUP_ORDER = [
  "Public",
  "Client",
  "Designer",
  "Account",
  "System",
];
