import Bridal1 from "@/assets/bridal/bridal_dress1.jpeg";
import Bridal2 from "@/assets/bridal/bridal_dress2.jpeg";
import Bridal3 from "@/assets/bridal/bridal_dress3.jpeg";
import Bridal4 from "@/assets/bridal/bridal_dress4.jpeg";
import Bridal5 from "@/assets/bridal/bridal_dress5.jpeg";
import Bridal6 from "@/assets/bridal/bridal_dress6.jpeg";
import Bridal7 from "@/assets/bridal/bridal_dress7.jpeg";
import Bridal8 from "@/assets/bridal/bridal_dress8.jpeg";
import Casual1 from "@/assets/casual/Casual1.jpg";
import Casual2 from "@/assets/casual/Casual2.jpeg";
import Casual3 from "@/assets/casual/Casual3.jpeg";
import Casual4 from "@/assets/casual/Casual4.jpeg";
import Casual5 from "@/assets/casual/Casual5.jpeg";
import Corp1 from "@/assets/corporate/Corp1.jpg";
import Corp2 from "@/assets/corporate/Corp2.jpeg";
import Corp3 from "@/assets/corporate/Corp3.jpeg";
import Corp4 from "@/assets/corporate/Corp4.jpeg";
import Corp5 from "@/assets/corporate/Corp5.jpeg";
import Corp6 from "@/assets/corporate/Corp6.jpeg";
import Corp7 from "@/assets/corporate/Corp7.jpeg";
import Corp8 from "@/assets/corporate/Corp8.jpeg";
import Corp9 from "@/assets/corporate/Corp9.jpeg";
import Corp10 from "@/assets/corporate/Corp10.jpeg";
import Corp11 from "@/assets/corporate/Corp11.jpeg";
import Corp12 from "@/assets/corporate/Corp12.jpeg";
import Corp13 from "@/assets/corporate/Corp13.jpeg";
import Corp14 from "@/assets/corporate/Corp14.jpeg";
import Corp15 from "@/assets/corporate/Corp15.jpeg";
import Kid1 from "@/assets/kids/Kid1.jpg";
import Kid2 from "@/assets/kids/Kid2.jpeg";
import Kid3 from "@/assets/kids/Kid3.jpeg";
import Kid4 from "@/assets/kids/Kid4.jpeg";
import Kid5 from "@/assets/kids/Kid5.jpeg";
import Kid6 from "@/assets/kids/Kid6.jpeg";
import Kid7 from "@/assets/kids/Kid7.jpeg";
import Kid8 from "@/assets/kids/Kid8.jpeg";
import Kid9 from "@/assets/kids/Kid9.jpeg";
import Kid10 from "@/assets/kids/Kid10.jpeg";
import Maternity1 from "@/assets/maternity/Maternity_1.jpeg";
import Maternity2 from "@/assets/maternity/Maternity_2.jpeg";
import Maternity3 from "@/assets/maternity/Maternity_3.jpeg";
import Maternity4 from "@/assets/maternity/Maternity_4.jpeg";
import Maternity5 from "@/assets/maternity/Maternity_5.jpeg";
import Party1 from "@/assets/party/Party_1.jpeg";
import Party2 from "@/assets/party/Party_2.jpeg";
import Party3 from "@/assets/party/Party_3.jpeg";
import Party4 from "@/assets/party/Party_4.jpeg";
import Party5 from "@/assets/party/Party_5.jpeg";
import Party6 from "@/assets/party/Party_6.jpeg";
import Party7 from "@/assets/party/Party_7.jpeg";
import Street1 from "@/assets/street/Street_1.jpeg";
import Street2 from "@/assets/street/Street_2.jpg";
import Street3 from "@/assets/street/Street_3.jpeg";
import Summer1 from "@/assets/summer/Sum_1.jpeg";
import Summer2 from "@/assets/summer/Sum_2.jpeg";
import Summer3 from "@/assets/summer/Sum_3.jpeg";
import Summer4 from "@/assets/summer/Sum_4.jpeg";
import Summer5 from "@/assets/summer/Sum_5.jpeg";
import Summer6 from "@/assets/summer/Sum_6.jpeg";
import Summer7 from "@/assets/summer/Sum_7.jpeg";
import Summer8 from "@/assets/summer/Sum_8.jpeg";
import Summer9 from "@/assets/summer/Sum_9.jpeg";

export default [
  {
    id: 1,
    name: "Elegant Evening Gown",
    description:
      "A stunning floor-length gown with intricate beadwork, perfect for formal events",
    price: 850,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Bridal1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 32,
    tags: ["Formal", "Evening", "Customizable"],
    category: "Formal Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 2,
    name: "Classic Business Suit",
    description:
      "Tailored women's suit with modern cut for professional settings",
    price: 750,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Bridal2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 28,
    tags: ["Formal", "Office", "Tailored"],
    category: "Formal Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 3,
    name: "Silk Cocktail Dress",
    description:
      "Mid-length dress with flowing silk fabric for semi-formal occasions",
    price: 680,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Bridal3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 19,
    tags: ["Formal", "Party", "Elegant"],
    category: "Formal Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 4,
    name: "Kente Two-Piece Set",
    description: "Traditional Ghanaian kente outfit with modern styling",
    price: 920,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Bridal4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 41,
    tags: ["Traditional", "Cultural", "Handwoven"],
    category: "Traditional Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 5,
    name: "Modern Batakari Outfit",
    description: "Contemporary take on the classic northern Ghanaian attire",
    price: 850,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Bridal5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 23,
    tags: ["Traditional", "Cultural", "Handmade"],
    category: "Traditional Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 6,
    name: "Casual Denim Jumpsuit",
    description: "Comfortable yet stylish one-piece for everyday wear",
    price: 450,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Bridal6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 17,
    tags: ["Casual", "Denim", "Versatile"],
    category: "Casual Wear",
    featured: true,
    bestSeller: false,
  },
  {
    id: 7,
    name: "Linen Shirt and Shorts Set",
    description: "Breathable summer outfit perfect for hot weather",
    price: 380,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Bridal7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 24,
    tags: ["Casual", "Summer", "Comfort"],
    category: "Casual Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 8,
    name: "Bridal Gown with Train",
    description: "Luxurious wedding dress with 3-foot train and lace detailing",
    price: 980,
    designerId: 4,
    designerName: "Mavis Okyere",
    image: Bridal8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 38,
    tags: ["Bridal", "Wedding", "Luxury"],
    category: "Wedding Dresses",
    featured: true,
    bestSeller: true,
  },
  {
    id: 9,
    name: "A-Line Casual Dress",
    description: "Flattering everyday dress with pockets for convenience",
    price: 320,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Casual1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.4,
    reviews: 15,
    tags: ["Casual", "Everyday", "Comfortable"],
    category: "Casual Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 10,
    name: "Traditional Smock Top",
    description: "Handwoven smock top with intricate northern patterns",
    price: 550,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Casual2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 21,
    tags: ["Traditional", "Cultural", "Handmade"],
    category: "Traditional Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 11,
    name: "Kids' Playtime Outfit",
    description: "Durable and colorful 2-piece set for active children",
    price: 280,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Casual3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 12,
    tags: ["Kids", "Playful", "Durable"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 12,
    name: "Formal Pantsuit",
    description: "Sharp-looking pantsuit for important business meetings",
    price: 790,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Casual4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 26,
    tags: ["Formal", "Business", "Professional"],
    category: "Formal Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 13,
    name: "Casual Weekend Joggers",
    description: "Comfortable joggers with elastic waistband",
    price: 250,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Casual5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.3,
    reviews: 18,
    tags: ["Casual", "Comfort", "Athleisure"],
    category: "Casual Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 14,
    name: "Corporate Blazer Dress",
    description: "Sleek dress with blazer styling for office wear",
    price: 670,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Corp1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 22,
    tags: ["Formal", "Office", "Tailored"],
    category: "Formal Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 15,
    name: "Traditional Kaba and Slit",
    description: "Modern interpretation of classic Ghanaian style",
    price: 720,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Corp2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 35,
    tags: ["Traditional", "Cultural", "Elegant"],
    category: "Traditional Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 16,
    name: "Kids' School Uniform Set",
    description: "Durable school uniform with reinforced knees",
    price: 310,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Corp3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 14,
    tags: ["Kids", "School", "Durable"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 17,
    name: "Bridal Party Dress",
    description: "Elegant bridesmaid dress available in multiple colors",
    price: 580,
    designerId: 4,
    designerName: "Mavis Okyere",
    image: Corp4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 29,
    tags: ["Bridal", "Wedding", "Party"],
    category: "Wedding Dresses",
    featured: false,
    bestSeller: true,
  },
  {
    id: 18,
    name: "Formal Evening Wrap Dress",
    description: "Chic wrap dress for cocktail parties and dinners",
    price: 690,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Corp5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 21,
    tags: ["Formal", "Evening", "Elegant"],
    category: "Formal Wear",
    featured: true,
    bestSeller: false,
  },
  {
    id: 19,
    name: "Traditional Agbada Set",
    description: "Luxurious three-piece outfit for special occasions",
    price: 890,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Corp6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 27,
    tags: ["Traditional", "Cultural", "Luxury"],
    category: "Traditional Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 20,
    name: "Casual Graphic Tee and Jeans",
    description: "Trendy outfit featuring custom graphic print",
    price: 350,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Corp7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.4,
    reviews: 16,
    tags: ["Casual", "Trendy", "Comfortable"],
    category: "Casual Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 21,
    name: "Kids' Party Dress",
    description: "Adorable frilly dress for special occasions",
    price: 420,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Corp8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 19,
    tags: ["Kids", "Party", "Dressy"],
    category: "Children's Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 22,
    name: "Mermaid Wedding Gown",
    description: "Figure-hugging bridal dress with lace appliqué",
    price: 950,
    designerId: 4,
    designerName: "Mavis Okyere",
    image: Corp9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 42,
    tags: ["Bridal", "Wedding", "Luxury"],
    category: "Wedding Dresses",
    featured: true,
    bestSeller: true,
  },
  {
    id: 23,
    name: "Formal High-Low Dress",
    description: "Stylish high-low hem dress for semi-formal events",
    price: 720,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Corp10,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 23,
    tags: ["Formal", "Party", "Trendy"],
    category: "Formal Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 24,
    name: "Traditional Fugu Shirt",
    description: "Handwoven shirt with northern Ghanaian patterns",
    price: 480,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Corp11,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Traditional", "Cultural", "Handmade"],
    category: "Traditional Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 25,
    name: "Casual Romper",
    description: "One-piece summer romper with adjustable straps",
    price: 290,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Corp12,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 14,
    tags: ["Casual", "Summer", "Comfortable"],
    category: "Casual Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 26,
    name: "Kids' Traditional Outfit",
    description: "Miniature traditional wear for special occasions",
    price: 380,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Corp13,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 16,
    tags: ["Kids", "Traditional", "Cultural"],
    category: "Children's Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 27,
    name: "Ball Gown Wedding Dress",
    description: "Princess-style wedding dress with full skirt",
    price: 1000,
    designerId: 4,
    designerName: "Mavis Okyere",
    image: Corp14,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 47,
    tags: ["Bridal", "Wedding", "Luxury"],
    category: "Wedding Dresses",
    featured: true,
    bestSeller: true,
  },
  {
    id: 28,
    name: "Formal Jumpsuit",
    description: "Elegant one-piece for formal occasions",
    price: 650,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Corp15,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 19,
    tags: ["Formal", "Evening", "Trendy"],
    category: "Formal Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 29,
    name: "Kids' Play Clothes Set",
    description: "Comfortable 3-piece set for active play",
    price: 320,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Kid1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 13,
    tags: ["Kids", "Play", "Durable"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 30,
    name: "Traditional Kente Gown",
    description: "Floor-length gown made with authentic kente cloth",
    price: 880,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Kid2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 31,
    tags: ["Traditional", "Cultural", "Luxury"],
    category: "Traditional Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 31,
    name: "Kids' Animal Print Set",
    description: "Adorable 2-piece set with fun animal prints for playtime",
    price: 320,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Kid3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 14,
    tags: ["Kids", "Playful", "Comfortable"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 32,
    name: "Traditional Kids' Kente",
    description: "Miniature kente outfit for cultural events",
    price: 380,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Kid4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 18,
    tags: ["Kids", "Traditional", "Cultural"],
    category: "Children's Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 33,
    name: "Kids' Denim Overalls",
    description: "Durable denim overalls with reinforced knees",
    price: 290,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Kid5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 12,
    tags: ["Kids", "Durable", "Play"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 34,
    name: "Kids' Formal Suit Set",
    description: "Miniature suit perfect for weddings and special occasions",
    price: 420,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Kid6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 16,
    tags: ["Kids", "Formal", "Special Occasion"],
    category: "Children's Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 35,
    name: "Kids' Raincoat Set",
    description: "Colorful waterproof set for rainy days",
    price: 350,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Kid7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 11,
    tags: ["Kids", "Rainwear", "Practical"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 36,
    name: "Kids' Casual Joggers Set",
    description: "Comfortable 2-piece for everyday wear",
    price: 270,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Kid8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.4,
    reviews: 9,
    tags: ["Kids", "Casual", "Comfort"],
    category: "Children's Wear",
    featured: false,
    bestSeller: false,
  },
  {
    id: 37,
    name: "Kids' Traditional Smock",
    description: "Handwoven smock in child sizes",
    price: 410,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Kid9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 15,
    tags: ["Kids", "Traditional", "Handmade"],
    category: "Children's Wear",
    featured: false,
    bestSeller: true,
  },
  {
    id: 38,
    name: "Kids' Princess Dress",
    description: "Sparkly dress for special occasions",
    price: 380,
    designerId: 5,
    designerName: "Olivia Taylor",
    image: Kid10,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 21,
    tags: ["Kids", "Dressy", "Special Occasion"],
    category: "Children's Wear",
    featured: true,
    bestSeller: true,
  },
  {
    id: 39,
    name: "Maternity Wrap Dress",
    description: "Flattering dress that grows with your bump",
    price: 520,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Maternity1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 28,
    tags: ["Maternity", "Comfort", "Versatile"],
    category: "Maternity",
    featured: true,
    bestSeller: true,
  },
  {
    id: 40,
    name: "Nursing-Friendly Top",
    description: "Discreet nursing access with stylish design",
    price: 380,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Maternity2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 32,
    tags: ["Maternity", "Nursing", "Practical"],
    category: "Maternity",
    featured: true,
    bestSeller: true,
  },
  {
    id: 41,
    name: "Maternity Jeans",
    description: "Stylish jeans with adjustable belly panel",
    price: 450,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Maternity3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 24,
    tags: ["Maternity", "Denim", "Comfort"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 42,
    name: "Formal Maternity Gown",
    description: "Elegant dress for special occasions during pregnancy",
    price: 680,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Maternity4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 19,
    tags: ["Maternity", "Formal", "Special Occasion"],
    category: "Maternity",
    featured: true,
    bestSeller: true,
  },
  {
    id: 43,
    name: "Maternity Kaftan",
    description: "Flowy traditional-inspired maternity wear",
    price: 490,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Maternity5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 17,
    tags: ["Maternity", "Traditional", "Comfort"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 44,
    name: "Sequined Party Dress",
    description: "Eye-catching dress for special events",
    price: 720,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Party1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 26,
    tags: ["Party", "Formal", "Glamorous"],
    category: "Party",
    featured: true,
    bestSeller: true,
  },
  {
    id: 45,
    name: "Cocktail Party Jumpsuit",
    description: "Chic one-piece for semi-formal events",
    price: 650,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Party2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 19,
    tags: ["Party", "Trendy", "Modern"],
    category: "Party",
    featured: false,
    bestSeller: true,
  },
  {
    id: 46,
    name: "Traditional Party Agbada",
    description: "Luxurious outfit for cultural celebrations",
    price: 890,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Party3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 31,
    tags: ["Party", "Traditional", "Cultural"],
    category: "Party",
    featured: true,
    bestSeller: true,
  },
  {
    id: 47,
    name: "Casual Party Top",
    description: "Stylish top perfect for informal gatherings",
    price: 380,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Party4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 14,
    tags: ["Party", "Casual", "Versatile"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 48,
    name: "Bridal Shower Dress",
    description: "Elegant dress for wedding-related events",
    price: 580,
    designerId: 4,
    designerName: "Mavis Okyere",
    image: Party5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 23,
    tags: ["Party", "Bridal", "Formal"],
    category: "Party",
    featured: true,
    bestSeller: true,
  },
  {
    id: 49,
    name: "Graduation Party Gown",
    description: "Elegant gown for graduation celebrations",
    price: 750,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Party6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 27,
    tags: ["Party", "Formal", "Special Occasion"],
    category: "Party",
    featured: true,
    bestSeller: true,
  },
  {
    id: 50,
    name: "Traditional Party Kaba",
    description: "Modern take on classic Ghanaian style",
    price: 680,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Party7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 22,
    tags: ["Party", "Traditional", "Cultural"],
    category: "Party",
    featured: false,
    bestSeller: true,
  },
  {
    id: 51,
    name: "Streetwear Hoodie Set",
    description: "Trendy oversized hoodie with matching pants",
    price: 420,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Street1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Street", "Casual", "Comfortable"],
    category: "Street",
    featured: false,
    bestSeller: true,
  },
  {
    id: 52,
    name: "Graphic Print Street Tee",
    description: "Bold graphic tee with urban aesthetic",
    price: 290,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Street2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 15,
    tags: ["Street", "Trendy", "Urban"],
    category: "Street",
    featured: false,
    bestSeller: false,
  },
  {
    id: 53,
    name: "Cargo Street Pants",
    description: "Utility pants with multiple pockets",
    price: 380,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Street3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 21,
    tags: ["Street", "Utility", "Trendy"],
    category: "Street",
    featured: true,
    bestSeller: true,
  },
  {
    id: 54,
    name: "Linen Summer Dress",
    description: "Breathable dress perfect for hot weather",
    price: 450,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Summer1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 24,
    tags: ["Summer", "Casual", "Comfortable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 55,
    name: "Floral Summer Romper",
    description: "One-piece with vibrant tropical print",
    price: 380,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Summer2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 19,
    tags: ["Summer", "Playful", "Trendy"],
    category: "Summer",
    featured: false,
    bestSeller: true,
  },
  {
    id: 56,
    name: "Traditional Summer Smock",
    description: "Lightweight handwoven top for warm weather",
    price: 520,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Summer3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 22,
    tags: ["Summer", "Traditional", "Breathable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 57,
    name: "Summer Linen Shirt",
    description: "Lightweight button-down for men and women",
    price: 420,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Summer4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.5,
    reviews: 17,
    tags: ["Summer", "Casual", "Versatile"],
    category: "Summer",
    featured: false,
    bestSeller: false,
  },
  {
    id: 58,
    name: "Beach Cover-Up Dress",
    description: "Flowy dress perfect for beach outings",
    price: 350,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Summer5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.7,
    reviews: 21,
    tags: ["Summer", "Beach", "Casual"],
    category: "Summer",
    featured: false,
    bestSeller: true,
  },
  {
    id: 59,
    name: "Formal Summer Dress",
    description: "Elegant yet breathable dress for summer events",
    price: 680,
    designerId: 1,
    designerName: "Ruth Asiedua",
    image: Summer6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 26,
    tags: ["Summer", "Formal", "Special Occasion"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 60,
    name: "Traditional Summer Kaftan",
    description: "Flowy cultural-inspired summer wear",
    price: 580,
    designerId: 2,
    designerName: "Victoria Yeboah",
    image: Summer7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 29,
    tags: ["Summer", "Traditional", "Cultural"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 61,
    name: "Summer Shorts Set",
    description: "Comfortable 2-piece for hot weather",
    price: 320,
    designerId: 3,
    designerName: "Beatrice Apaloo",
    image: Summer8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Summer", "Casual", "Comfortable"],
    category: "Summer",
    featured: false,
    bestSeller: false,
  },
  {
    id: 62,
    name: "Summer Wedding Guest Dress",
    description: "Breathable formal dress for warm weather weddings",
    price: 720,
    designerId: 4,
    designerName: "Mavis Okyere",
    image: Summer9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Formal", "Wedding"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
];