import Bridal1 from "@/assets/bridal/bridal_dress1.jpeg";
import Bridal2 from "@/assets/bridal/bridal_dress2.jpeg";
import Bridal3 from "@/assets/bridal/bridal_dress3.jpeg";
import Bridal4 from "@/assets/bridal/bridal_dress4.jpeg";
import Bridal5 from "@/assets/bridal/bridal_dress5.jpeg";
import Bridal6 from "@/assets/bridal/bridal_dress6.jpeg";
import Bridal7 from "@/assets/bridal/bridal_dress7.jpeg";
import Bridal8 from "@/assets/bridal/bridal_dress8.jpeg";
import Casual1 from "@/assets/casual/Casual1.jpg";
import Casual2 from "@/assets/casual/Casual2.jpeg";
import Casual3 from "@/assets/casual/Casual3.jpeg";
import Casual4 from "@/assets/casual/Casual4.jpeg";
import Casual5 from "@/assets/casual/Casual5.jpeg";
import Corp1 from "@/assets/corporate/Corp1.jpg";
import Corp2 from "@/assets/corporate/Corp2.jpeg";
import Corp3 from "@/assets/corporate/Corp3.jpeg";
import Corp4 from "@/assets/corporate/Corp4.jpeg";
import Corp5 from "@/assets/corporate/Corp5.jpeg";
import Corp6 from "@/assets/corporate/Corp6.jpeg";
import Corp7 from "@/assets/corporate/Corp7.jpeg";
import Corp8 from "@/assets/corporate/Corp8.jpeg";
import Corp9 from "@/assets/corporate/Corp9.jpeg";
import Corp10 from "@/assets/corporate/Corp10.jpeg";
import Corp11 from "@/assets/corporate/Corp11.jpeg";
import Corp12 from "@/assets/corporate/Corp12.jpeg";
import Corp13 from "@/assets/corporate/Corp13.jpeg";
import Corp14 from "@/assets/corporate/Corp14.jpeg";
import Corp15 from "@/assets/corporate/Corp15.jpeg";
import Kid1 from "@/assets/kids/Kid1.jpg";
import Kid2 from "@/assets/kids/Kid2.jpeg";
import Kid3 from "@/assets/kids/Kid3.jpeg";
import Kid4 from "@/assets/kids/Kid4.jpeg";
import Kid5 from "@/assets/kids/Kid5.jpeg";
import Kid6 from "@/assets/kids/Kid6.jpeg";
import Kid7 from "@/assets/kids/Kid7.jpeg";
import Kid8 from "@/assets/kids/Kid8.jpeg";
import Kid9 from "@/assets/kids/Kid9.jpeg";
import Kid10 from "@/assets/kids/Kid10.jpeg";
import Maternity1 from "@/assets/maternity/Maternity_1.jpeg";
import Maternity2 from "@/assets/maternity/Maternity_2.jpeg";
import Maternity3 from "@/assets/maternity/Maternity_3.jpeg";
import Maternity4 from "@/assets/maternity/Maternity_4.jpeg";
import Maternity5 from "@/assets/maternity/Maternity_5.jpeg";
import Party1 from "@/assets/party/Party_1.jpeg";
import Party2 from "@/assets/party/Party_2.jpeg";
import Party3 from "@/assets/party/Party_3.jpeg";
import Party4 from "@/assets/party/Party_4.jpeg";
import Party5 from "@/assets/party/Party_5.jpeg";
import Party6 from "@/assets/party/Party_6.jpeg";
import Party7 from "@/assets/party/Party_7.jpeg";
import Party8 from "@/assets/party/Party_8.jpg";
import Party9 from "@/assets/party/Party_9.jpeg";
import Party10 from "@/assets/party/Party_10.jpeg";
import Party11 from "@/assets/party/Party_11.jpeg";
import Street1 from "@/assets/street/Street_1.jpeg";
import Street2 from "@/assets/street/Street_2.jpg";
import Street3 from "@/assets/street/Street_3.jpeg";
import Summer1 from "@/assets/summer/Sum_1.jpeg";
import Summer2 from "@/assets/summer/Sum_2.jpeg";
import Summer3 from "@/assets/summer/Sum_3.jpeg";
import Summer4 from "@/assets/summer/Sum_4.jpeg";
import Summer5 from "@/assets/summer/Sum_5.jpeg";
import Summer6 from "@/assets/summer/Sum_6.jpeg";
import Summer7 from "@/assets/summer/Sum_7.jpeg";
import Summer8 from "@/assets/summer/Sum_8.jpeg";
import Summer9 from "@/assets/summer/Sum_9.jpeg";

export default [
  { 
    id: 1,
    name: "Bridal Dress 1",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 2,
    name: "Bridal Dress 2",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 3,
    name: "Bridal Dress 3",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 4,
    name: "Bridal Dress 4",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 5,
    name: "Bridal Dress 5",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 6,
    name: "Bridal Dress 6",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 7,
    name: "Bridal Dress 7",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 8,
    name: "Bridal Dress 8",
    description:
      "A stunning floor-length gown perfect for formal events and galas",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Bridal8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Bridal", "Wedding", "Customizable"],
    category: "Bridal",
    featured: true,
    bestSeller: true,
  },
  {
    id: 9,
    name: "Casual Wear 1",
    description: "Stylish and versatile cloths for everyday casual wear",
    price: 300,
    designerId: 2,
    designerName: "Sophia Chen",
    image: Casual1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Casual", "Daily", "Everyday"],
    category: "Casual",
    featured: true,
    bestSeller: false,
  },
  {
    id: 10,
    name: "Casual Wear 2",
    description: "Stylish and versatile cloths for everyday casual wear",
    price: 300,
    designerId: 2,
    designerName: "Sophia Chen",
    image: Casual2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Casual", "Daily", "Everyday"],
    category: "Casual",
    featured: true,
    bestSeller: false,
  },
  {
    id: 11,
    name: "Casual Wear 3",
    description: "Stylish and versatile cloths for everyday casual wear",
    price: 300,
    designerId: 2,
    designerName: "Sophia Chen",
    image: Casual3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Casual", "Daily", "Everyday"],
    category: "Casual",
    featured: true,
    bestSeller: false,
  },
  {
    id: 12,
    name: "Casual Wear 4",
    description: "Stylish and versatile cloths for everyday casual wear",
    price: 300,
    designerId: 2,
    designerName: "Sophia Chen",
    image: Casual4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Casual", "Daily", "Everyday"],
    category: "Casual",
    featured: true,
    bestSeller: false,
  },
  {
    id: 13,
    name: "Casual Wear 5",
    description: "Stylish and versatile cloths for everyday casual wear",
    price: 300,
    designerId: 2,
    designerName: "Sophia Chen",
    image: Casual5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.6,
    reviews: 18,
    tags: ["Casual", "Daily", "Everyday"],
    category: "Casual",
    featured: true,
    bestSeller: false,
  },
  {
    id: 14,
    name: "Corporate Wear 1",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 15,
    name: "Corporate Wear 2",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 16,
    name: "Corporate Wear 3",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 17,
    name: "Corporate Wear 4",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 18,
    name: "Corporate Wear 5",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 19,
    name: "Corporate Wear 6",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 20,
    name: "Corporate Wear 7",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 21,
    name: "Corporate Wear 8",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 22,
    name: "Corporate Wear 9",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 23,
    name: "Corporate Wear 10",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp10,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 24,
    name: "Corporate Wear 11",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp11,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 25,
    name: "Corporate Wear 12",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp12,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 26,
    name: "Corporate Wear 13",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp13,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 27,
    name: "Corporate Wear 14",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp14,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 28,
    name: "Corporate Wear 15",
    description: "Professional attire for the modern business person",
    price: 600,
    designerId: 5,
    designerName: "Priya Sharma",
    image: Corp15,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 5.0,
    reviews: 28,
    tags: ["Corporate", "Formal", "Cultural"],
    category: "Corporate",
    featured: false,
    bestSeller: true,
  },
  {
    id: 29,
    name: "Kidz Clothes 1",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 30,
    name: "Kidz Clothes 2",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 31,
    name: "Kidz Clothes 3",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 32,
    name: "Kidz Clothes 4",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 33,
    name: "Kidz Clothes 5",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 34,
    name: "Kidz Clothes 6",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 35,
    name: "Kidz Clothes 7",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 36,
    name: "Kidz Clothes 8",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 37,
    name: "Kidz Clothes 9",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 38,
    name: "Kidz Clothes 10",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Kid10,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Kids", "Playful", "Tailored"],
    category: "Kids",
    featured: false,
    bestSeller: false,
  },
  {
    id: 39,
    name: "Maternal Clothes 1",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Maternity1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Pregnant", "Mothers", "Tailored"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 40,
    name: "Maternal Clothes 2",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Maternity2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Pregnant", "Mothers", "Tailored"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 41,
    name: "Maternal Clothes 3",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Maternity3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Pregnant", "Mothers", "Tailored"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 42,
    name: "Maternal Clothes 4",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Maternity4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Pregnant", "Mothers", "Tailored"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 43,
    name: "Maternal Clothes 5",
    description: "Cute and colorful clothes for kids",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Maternity5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Pregnant", "Mothers", "Tailored"],
    category: "Maternity",
    featured: false,
    bestSeller: false,
  },
  {
    id: 44,
    name: "Party Wear 1",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 45,
    name: "Party Wear 2",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 46,
    name: "Party Wear 3",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 47,
    name: "Party Wear 4",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 48,
    name: "Party Wear 5",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 49,
    name: "Party Wear 6",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 50,
    name: "Party Wear 7",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 51,
    name: "Party Wear 8",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 52,
    name: "Party Wear 9",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 53,
    name: "Party Wear 10",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party10,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 54,
    name: "Party Wear 11",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Party11,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Party", "Fun", "Tailored"],
    category: "Party",
    featured: false,
    bestSeller: false,
  },
  {
    id: 55,
    name: "Street Wear 1",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Street1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Street", "fashion", "Tailored"],
    category: "Street",
    featured: false,
    bestSeller: false,
  },
  {
    id: 56,
    name: "Street Wear 2",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Street2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Street", "fashion", "Tailored"],
    category: "Street",
    featured: false,
    bestSeller: false,
  },
  {
    id: 57,
    name: "Street Wear 3",
    description: "Stylish and colorful clothes for parties and events",
    price: 750,
    designerId: 3,
    designerName: "James Mitchell",
    image: Street3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.9,
    reviews: 12,
    tags: ["Street", "fashion", "Tailored"],
    category: "Street",
    featured: false,
    bestSeller: false,
  },
  {
    id: 58,
    name: "Summer Wear 1",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer1,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 59,
    name: "Summer Wear 2",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer2,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 60,
    name: "Summer Wear 3",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer3,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 61,
    name: "Summer Wear 4",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer4,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 62,
    name: "Summer Wear 5",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer5,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 63,
    name: "Summer Wear 6",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer6,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 64,
    name: "Summer Wear 7",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer7,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 65,
    name: "Summer Wear 8",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer8,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
  {
    id: 66,
    name: "Summer Wear 9",
    description: "Stylish and colorful clothes for the summer",
    price: 450,
    designerId: 1,
    designerName: "Emma Wilson",
    image: Summer9,
    gallery: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    rating: 4.8,
    reviews: 24,
    tags: ["Summer", "Informal", "Customizable"],
    category: "Summer",
    featured: true,
    bestSeller: true,
  },
]