import { ref } from "vue";

// This creates a reactive clients array that can be shared across components
export const clients = ref([
  {
    id: 1,
    name: "Jane Doe",
    email: "jane.doe@example.com",
    location: "New York, USA",
    lastOrder: "Mar 15, 2025",
    totalOrders: 8,
    totalSpent: "$1,200.00",
    status: "Active",
    selected: false,
  },
  {
    id: 2,
    name: "John Smith",
    email: "john.smith@example.com",
    location: "Los Angeles, USA",
    lastOrder: "Mar 14, 2025",
    totalOrders: 12,
    totalSpent: "$2,450.00",
    status: "Active",
    selected: false,
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.j@example.com",
    location: "London, UK",
    lastOrder: "Mar 13, 2025",
    totalOrders: 3,
    totalSpent: "$650.00",
    status: "New",
    selected: false,
  },
  {
    id: 4,
    name: "Robert Wilson",
    email: "robert.w@example.com",
    location: "Chicago, USA",
    lastOrder: "Mar 10, 2025",
    totalOrders: 6,
    totalSpent: "$980.00",
    status: "Active",
    selected: false,
  },
  {
    id: 5,
    name: "Sarah Davis",
    email: "sarah.d@example.com",
    location: "Toronto, Canada",
    lastOrder: "Mar 5, 2025",
    totalOrders: 2,
    totalSpent: "$350.00",
    status: "New",
    selected: false,
  },
  {
    id: 6,
    name: "Michael Brown",
    email: "michael.b@example.com",
    location: "Sydney, Australia",
    lastOrder: "Mar 3, 2025",
    totalOrders: 4,
    totalSpent: "$720.00",
    status: "Active",
    selected: false,
  },
  {
    id: 7,
    name: "Lisa Garcia",
    email: "lisa.g@example.com",
    location: "Miami, USA",
    lastOrder: "Feb 28, 2025",
    totalOrders: 1,
    totalSpent: "$150.00",
    status: "New",
    selected: false,
  },
  {
    id: 8,
    name: "David Miller",
    email: "david.m@example.com",
    location: "Berlin, Germany",
    lastOrder: "Feb 25, 2025",
    totalOrders: 9,
    totalSpent: "$1,820.00",
    status: "Active",
    selected: false,
  },
  {
    id: 9,
    name: "Alice Johnson",
    email: "alice@example.com",
    phone: "+1234567890",
    location: "New York, NY",
    joinedDate: "2023-01-10",
    totalSpent: 200.0,
    status: "active",
    avatarUrl: "path/to/image1.jpg",
  },

  {
    id: 10,
    name: "Bob Smith",
    email: "bob@example.com",
    phone: "+0987654321",
    location: "Los Angeles, CA",
    joinedDate: "2023-01-15",
    totalSpent: 150.0,
    status: "active",
    avatarUrl: "path/to/image2.jpg",
  },

  {
    id: 11,
    name: "Charlie Brown",
    email: "charlie@example.com",
    phone: "+1122334455",
    location: "Chicago, IL",
    joinedDate: "2022-12-20",
    totalSpent: 220.0,
    status: "inactive",
    avatarUrl: "path/to/image3.jpg",
  },

  {
    id: 12,
    name: "David Wilson",
    email: "david@example.com",
    phone: "+2233445566",
    location: "Houston, TX",
    joinedDate: "2023-02-05",
    totalSpent: 300.0,
    status: "active",
    avatarUrl: "path/to/image4.jpg",
  },

  {
    id: 13,
    name: "Eve Davis",
    email: "eve@example.com",
    phone: "+3344556677",
    location: "Phoenix, AZ",
    joinedDate: "2023-03-15",
    totalSpent: 180.0,
    status: "active",
    avatarUrl: "path/to/image5.jpg",
  },

  {
    id: 14,
    name: "Frank Garcia",
    email: "frank@example.com",
    phone: "+4455667788",
    location: "Philadelphia, PA",
    joinedDate: "2023-04-01",
    totalSpent: 320.0,
    status: "active",
    avatarUrl: "path/to/image6.jpg",
  },

  {
    id: 15,
    name: "Grace Lee",
    email: "grace@example.com",
    phone: "+5566778899",
    location: "San Antonio, TX",
    joinedDate: "2023-05-10",
    totalSpent: 240.0,
    status: "inactive",
    avatarUrl: "path/to/image7.jpg",
  },

  {
    id: 16,
    name: "Hank Martinez",
    email: "hank@example.com",
    phone: "+6677889900",
    location: "San Diego, CA",
    joinedDate: "2023-06-12",
    totalSpent: 180.0,
    status: "active",
    avatarUrl: "path/to/image8.jpg",
  },

  {
    id: 17,
    name: "Ivy Nelson",
    email: "ivy@example.com",
    phone: "+7788990011",
    location: "Dallas, TX",
    joinedDate: "2023-07-14",
    totalSpent: 500.0,
    status: "active",
    avatarUrl: "path/to/image9.jpg",
  },

  {
    id: 18,
    name: "Jack Robinson",
    email: "jack@example.com",
    phone: "+8899001122",
    location: "San Jose, CA",
    joinedDate: "2023-08-20",
    totalSpent: 400.0,
    status: "active",
    avatarUrl: "path/to/image10.jpg",
  },
]);

// You can add store methods here as well
export function findClientById(id) {
  return clients.value.find((c) => c.id === parseInt(id));
}
